version: '3'

services:
  tempo:
    container_name: tempo
    image: grafana/tempo
    networks:
      - honeycomb_drone_network
    ports:
      - 9095:9095
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../tempo.yaml:/etc/tempo.yaml

