version: '3'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    networks:
      - honeycomb_drone_network

    ports:
     - '3000:3000'
    volumes:
      - './volumes/data:/var/lib/grafana'


    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    # entrypoint:
    #   - sh
    #   - -euc
    #   - |
    #     mkdir -p /etc/grafana/provisioning/datasources
    #     cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
    #     apiVersion: 1
    #     datasources:
    #     - name: Loki
    #       type: loki
    #       access: proxy
    #       orgId: 1
    #       url: http://127.0.0.1:3100
    #       basicAuth: false
    #       isDefault: false
    #       version: 1
    #       editable: false
    #     - name: Prometheus
    #       type: prometheus
    #       orgId: 1
    #       url: http://prometheus:9090
    #       basicAuth: false
    #       isDefault: true
    #       version: 1
    #       editable: false
    #     EOF
    #     /run.sh


volumes:
  grafana_storage: {}